### ISSUE TITLE
Add third row for the GitHub Actions Status in the Quick overview

### ISSUE THREAD

**Issue by kolioOtSofia** [hpi-swa-teaching/AutoTDD#55] opened 2021-05-15 08:52 UTC
As a `user` I want to have the same consistent design in the Quick overview Window for the GitHub Actions, so that the status can be displayed in a consistent way later on. 

### Accenptance Criteria
-[ ] There is a dedicated third row for the GitHub Actions in the Quick Overview

### Effort evaluation 
2 Points

**Comment by Benjamin-Frost** [comment] 2021-05-15 10:30
Duplicate of #42

**Closed** 2021-05-15 15:43 UTC
Labels: feature request, user story
